"""add markdown

Revision ID: 184436916af7
Revises: 51abd04d0b00
Create Date: 2016-05-25 12:22:15.682875

"""

# revision identifiers, used by Alembic.
revision = '184436916af7'
down_revision = '51abd04d0b00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
