"""add gravatar

Revision ID: 198d4b34cc35
Revises: 2da93ff07c69
Create Date: 2016-05-23 10:44:32.380260

"""

# revision identifiers, used by Alembic.
revision = '198d4b34cc35'
down_revision = '2da93ff07c69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
